[all]
0:0                 Spring 1940...
0:06
0:07 The might of our war machine is unstoppable!
0:20
0:34  Poland was swept aside...
0:40
0:41 Then we turned our guns west towards France...
0:48
1:04 ...and crushed all in our path.
1:10
1:25  Our advance is inexorable... 
1:30
1:31 ...Germany can never be defeated !
1:37
1:45 And yet there remains one final obstacle in our path...
1:50
2:00  BRITAIN!
2:04
2:05 But the Storms of War are blowing her way...
2:20



