[all]
0:05   As the summer progresses, so too, does the intensity of the RAF's             defence...
0:10
0:14 ...but still the bombers come on!
0:20
0:26 Despite the dangers...
0:35
0:40 despite the terrible opposition...
0:45
0:50 ...they bravely plough on through the danger-filled skies.
0:55
1:40 Each mission seemingly bringing them...
1:50
2:00 ...one step closer...
2:25
2:30 ...to their doom.
2:45

