[all]
0:00                 HELL'S  ANGELS  - the 303rd Bomb Group 
0:05                                By  STIBOO  
0:09                            www.Bigwing.net 
0:13                Special thanks to JaRink and Bakshi
0:17      Dedicated to the Original pilots and crews of the 303rd BG...
0:20             
0:21         LEAPIN' LIZ           missing in action January 1943        
0:26         JERSEY BOUNCE       scrapped May 1945    
0:33          SHAK HAK             missing in action February 1943
0:40          KALI                        missing in action January 1943                       
0:46        MEMPHIS TOT      missing in action February 1943     
0:53         SPOOK                   missing in action February 1943        
1:00        HUNGA DUNGA    missing in action March 1943    
1:07      SKY WOLF             missing in action January 1944   
1:13     THUMPER                 crash landed in England January 1943  
1:21      BEATS ME               missing in action January 1943
1:28     OooLD SOLJER      mid-air collision March 1943  
1:37      LADY FAIRWEATHER        missing in action  November 1942
1:44    THE '8' BALL                crash landed in England December 1942
1:52    THE GREEN HORNET      missing in action January 1943
2:01    SUSFU                        missing in action January 1943
2:08    BAD CHECK           missing in action January 1944
2:16    JOE BTFSPLK 2          missing in action May 1943
2:24    WEREWOLF         crash landed England  January 1943
2:32    ONE O'CLOCK JUMP       missing in action December 1942
2:40     HELL CAT                     missing in action January 1943
2:51     KNOCKOUT  DROPPER        the first B17 to complete 75 missions..
2:57           ...returned home to the USA March 1944
3:02
3:04        YEHUDI                     missing in action January 1943
3:11      HOLY MACKEREL          missing in action April 1943
3:18    THE DUCHESS                returned home to the USA July 1944
3:27   FDR'S POTATO PEELER KIDS          missing in action November 1943
3:35    ZOMBIE                   missing in action December 1942
3:42   THE DEVIL HIMSELF             returned home to the USA December 1944
3:50   S-FOR-SUGAR                missing in action  January 1944
3:57   no name                    transfered to other unit July 1943 
4:05   WULFE HOUND           missing in action December 1942   -    Flown by Luftwaffe
4:12    YARDBIRD                       missing in action May 1943
4:20     SNAP! CARCKLE! POP!            missing in action January 1943
4:27
4:30         and finally,    HELL'S ANGELS   and it's original crew...
4:35         returned home to a hero's welcome 20th January 1944






