[all]
0:00
0:10 We have been on Guadalcanal for 71 days.
0:15 
0:17 This will be the last time we take off from henderson feild.
0:22 
0:30 despite everything being thrown at us, kept henderson feild secure
0:33 in doing this we kept the bombers flying who challanged the Japanese at sea.
0:35 without them to harry the japanese ships, Guadalcanal would have been lost.
0:39 
0:45 it was not without cost though. For each of you who landed here on August 20th,
0:48 and are still with us today, another is not.
0:51 
0:55 Most of you will never see this island again. But it will forever leave an imprint on everyone.
0:59 
1:03 Everyone who fought in the sky, and on the ground, defending the Tenaru or defending henderson,
1:06 on Edson's ridge or above it.
1:08
1:09 For them, none of it shall be forgotten.