[all]
0:0
0:02  
0:10
0:12 The raid on Nakorn Bat airfield on the 24th was the last air action of the conflict.
0:20
0:22 Four Moranes rose to meet a force of Ki-30's with a Hawk 75 escort.
0:30 
0:32 The fighting on the ground had come to a halt on the outskirts of Batdambang.
0:40
0:42 The Japanese brokered a ceasefire which brought the fighting to an end.  
0:50
0:52 A formal treaty was finally ratified and became effective on the 31st January 1941.	
1:02
1:10 However, peace was not to last in the region.
1:12 
1:20 The Japanese had their own agenda. 
1:22 
1:30 
1:40 Their forces would soon occupy most of South East Asia.
1:42 
1:50 
1:52 I hope you have enjoyed this rather brief portrayal of a long forgotten war.
2:02 
2:10 
2:12 Dedicated to the fallen of all nations, let us not forget.
2:20 
2:22 
2:30	
2:32
2:40
2:42