[all]
0:0
0:02  
0:10
0:12 French Indochina, September 1940, your unit is E.C. 2/595.
0:20
0:22 You are the defenders of Vichy Frances colonial dominions.
0:30 
0:32 Japanese forces have been given access rights to French colonial lands in the region.
0:40
0:42 During September French recon aircraft spot a japanese military outpost near Lang.  
0:50
0:52 Going against diplomatic protocols, the japanese advance further into French Indochina.
1:02
1:10 
1:12 In neighbouring Thailand the Government is seeking the return of some if its territory. 
1:20
1:22 Land conquered by France at the turn of the Century it claims as its own.
1:30
1:32 The mix of interests in the region is a volatile one.
1:40
1:42 Anything could happen.
1:50
1:52 A semi historical campaign for the Vichy Air Force by Peter Shaw, aka Mission_bug.
2:02
2:10
2:12 