[all]
0:00   "Peace in our time" is a broken promise as Germany invades Poland in September 1939.
0:08     
0:12   Polish armies fight bravely but are overwhelmed by superior forces and equipment.
0:19
0:20   Many Polish soldiers escape to other countries in hopes of resuming the fight. 
0:28
0:30   They are disappointed. They are not welcome though they are experienced soldiers and pilots.
0:38
0:40   Romania joins the axis, so they venture to France.
0:49
0:50   In France they are ignored and in the Soviet Union treatment is worse.
0:59
0:60   The Poles in France go to England when the Germans attack.
1:10   The English think the Poles lack morale and discipline.
1:18
1:22   The Poles in the RAF are relegated to endless training missions...
1:28
1:30   Until necessity forces the RAF to use the Poles in combat.
1:38
1:40   Then the RAF sees the skills of pilots like those in RAF 303 Squadron.
1:52
1:54   Ko\u015Bciuszko  Squadron!	



