[all]
0:0   
0:01   After the losses suffered on August 31, the Squadron was pulled out... 
0:04   
0:05   ... an order we received with both relief and melancholy... 
0:08   
0:09   ... because we badly needed a breather...
0:12   
0:13   ... and at the same time we didn't want to give in to the Hun.
0:16
0:17   But we also knew that we soon would be back, ready for 
0:20
0:21   T H E   F I N A L   B A T T L E!

   
