[all]
0:0   
0:01   "What General Weygand called the Battle of France is over. 
0:04   
0:05   "I expect that the Battle of Britain is about to begin. 
0:08   
0:09   "Upon this battle depends the survival of Christian civilization. 
0:12   
0:13   "Upon it depends our own British life... 
0:16   "...and the long continuity of our institutions and our Empire. 
0:19
0:20   "The whole fury and might of the enemy must very soon be turned on us.
0:23
0:24   "Hitler knows that he will have to break us in this Island or lose the war."
0:28
0:29   - Winston Churchill, House of Commons, June 18, 1940
0:31
0:32   Yes, you are the ones that will bear the brunt of the attack. You are the...
0:35   F I G H T E R    B O Y S

   
