[all] 
00:05 Décembre 1941, la roue tourne pour l' Armée Rouge
00:10
00:15 Les Unités Sovietiques poursuivent leur reconquête du terrain occupé par les allemands.
00:20
00:25 Malgré des pertes catastrophiques, les chars Russes repoussent les Allemands vers Rhzev.
00:30
00:38 La Luftwaffe règne toujours en maître dans les cieux de Russie.
00:44
00:47 Les Allemands ont de meilleurs avions et tactiques, des pilotes expérimentés et confiants.
00:51
01:00 Mais à travers les coups durs reçus durant six mois,
01:04
01:07 certains pilotes Sovietiques ont survécu, et ils mènent maintenant le combat.
01:11
01:15 Les Allemands ont un avant-goût des difficultés à venir.
01:19
01:23 L' Armée de l' Air Soviétique relève doucement la tête....
01:28

