[all] 
00:05  juillet 43, saillant de Kurk.
00:11 Le duel entre la Luftwaffe et les VVS se poursuit.
00:17 Les pilotes des deux camps disparaissent un à un dans la fournaise.
00:23
00:27 La JG51, fer de lance de la Luftwaffe.
00:33 Ils ont perdu 63 avions en seulement 10 jours de combat.
00:38
00:41 De plus en plus d' Experten ne rentrent pas de mission.
00:46
00:51 Les pilotes Soviets, pour la plupart frais émoulus de l' école,
00:57 pilotent maintenant des avions modernes,
01:04 et petit à petit reprennnent le contrôle des airs aux Allemands.
01:10
01:20 L' emprise de la Luftwaffe sur le front de l' Est appartient au passé.
01:26
01:30 La victoire finale est encore loin.
01:37 Mais chauqe année qui passe est au bénéfice des Russes.
01:46
01:55 Leur talent ne parvient plus à sauver les Experten.
02:01 L' industrie Soviétique produit plusieurs milliers d' avion de pluis que l' Allemagne chaque mois.
02:07 La supériorité numérique Soviétique s' épelle ainsi:
02:14 K-
02:20 –A-
02:25 –PUT!
02:37 Les unités de la Wehrmacht, privées du soutien de la Luftwaffe,
02:44 commencent à sentir le poids des bombes, et la tenacité des pilotes d' assaut.
02:51




