[all] 
00:03 Eté 1944.
00:09 Les défenses de la Wehrmacht croulent sous les coups de boutoir des Soviets.
00:19 L’ acheminement de renforts fournis par l’ industrie Soviétique et le Lend-Lease est ininterrompu,
00:24 et c’ est un véritable fleuve de tanks, d’ artillerie et d’ avions 
00:30 qui alimente le front.
00:36 Les alliés de l’ Ouest ont enfin ouvert un second Front.
00:41
00:48 Les unités Allemandes sont forcées de se retirer,
00:53 abandonnant les positions si récemment conquises.
00:58
01:30 Et même lors de leur retraite, 
01:36 la Mort Noire plane sur eux.
01:42 Les Il-2 Sturmoviks sont constamment à l’ horizon.
01:47
01:55 La plupart des pilotes de Sturmoviks
02:00 étaient tués avant leur cinquième sortie.
02:06
02:30 A la mémoire des pilotes de Sturmoviks…
02:36




