[all]
00:03 Eté 1943
00:09 Le Front de l' Est est étragement calme.
00:16 La Wehrmacht prépare une nouvelle offensive: l'Operation Citadelle.
00:21
00:45 De nouveaux chars redoutables, les Pz V Panther et Pz VI Tiger,
00:51 y joueront un rôle prépondérant.
00:57 Les Panzers progressent lentement vers Koursk.
01:03
01:09 Durant avril et mai, les troupes attendaient, retranchées dans leurs abris.
01:15 Mais les aviateurs luttaient au-dessus pour le contrôle du ciel.
01:21 
01:24 Le 21 mai 1943, l' escadrille d' alerte de la JG51 Moelders
01:30 décolla vers le village de Rozhdestveno, 
01:36 où les colonnes de ravitaillement encombraient les routes.
01:42 
01:50 Les pilotes avaient des raisons d' être inquiets. 
01:56 Tout au long du mois de mai, les Sturmoviks avaient frappé fort.
02:02 Ils avaient détruit plusieurs dépôts Allemands autour d' Orel.
02:08 
02:15 Les observateurs et stations de radar Allemandes avaient donné l' alerte,
02:21 une importante formation de bombardiers approchait.
02:27
02:51 Le General Rudenko, commandant la 16ème Armée Aérienne,
02:58 avait envoyé une fois de plus les légendaires Pe-2 Peshkas à la bataille.
03:04
03:07 Les Experten de la Moelders tombèrent sur un gros morceau,
03:14 les As Soviériques d' un régiment de la Garde
03:21 Ces bombardiers ne seraient pas faciles à intercepter.
03:28
03:45 Une bataille aérienne acharnée commença.
03:53
04:55 Jusqu' ici les Russes pratiquaient le bombardement en piqué rarement et mal,
05:02 mais il y avait du changement dans l' air...
05:10
05:27 Les Gardes tinrent les 109 à distance des Pe-2;
05:34 
05:57 Un mois et demi plus tard,
06:03 la plus grande bataille de blindés de l' histoire se déroulait sous leurs ailes.
06:10
