[all] 
00:03 A l'été 44 Leningrad fut enfin libérée,
00:08
00:10 après un siège de 900 jours la ville revenait enfin à la vie.
00:15 
00:16 Mais les succès timides de l' Armée Rouge cet hiver
00:20 avaient à peine repoussé les Allemands au delà des murs de la ville.
00:24
00:28 Alors que la glace recule, les convois de l' Axe s' intensifient.
00:33 Ils ravitaillent leurs troupes de Carélie.
00:38
00:41 L'Aviation de la Flotte de la Baltique a une mission:
00:47 détruire les navires ennemis à la bombe et à la torpille.
00:53 Couper les lignes de ravitaillement.
00:59
01:05 Une tâche clairement définie, pas plus facile pour autant.
01:10
01:20 Bien qu' en effectif décroissant, la Luftwaffe est toujours forte.
01:25 La plupart des convois ont toujours un parapluie de chasseurs.
01:30
02:25 Les pertes des bombardiers Soviétiques augmentent chaque jour.
02:30
02:46 Les équipages sont trop peu entraînés.
02:51 Les bombes ne touchent que rarement leur cible.
02:56
03:25 Mais le moral des Soviets est toujours haut.
03:30
03:55 Dédié aux pilotes de la Marine qui ont servi lors de la deuxième guerre mondiale...
04:03


