[all]
0:01  Welcome to Biggin Hill Airfield. I'm Hugo Armstrong, squadron leader of 611.
0:05  This is your crate. A brand new Spitfire IX model.
0:10  Study carefully the pilot notes I gave you, and take her for a ride.
0:15  You'd better get well acquaintanced with her quickly
0:18  for my number 2 has just been shot down by a bloody 190
0:23  and I'm in a terrible need of a new wingman.
0:27  NOTE: YOU CAN FIND THE PILOT NOTES IN THE ZIP FILE OF THE CAMPAIGN  