[all]
0:00
0:01 January, 1945
0:05
0:06 The battle of the Bulge has been won.
0:12
0:13 487 squadron gets the distinguished unit citation...
0:21
0:22 the only unit in Europe to do so!
0:30
0:33 1.JaVA_Sjonnie would like to thank:
0:39
0:40 1.JaVA_Serval for the wonderful P-47 and P-51 skins
0:49
0:50 Canon_UK for the Bf109, FW190 and Me262 skins
0:58
0:59 1.JaVA_Platypus, Aero_Shodanjo and others for their skins
1:10
1:11 This campaign was tested by 1.JaVA_Platypus, TimHolt and... 
1:20
1:21 FoolTrottel, the all-seeing eye
1:29
1:30 Also, many thanks to Scott Flugum for historical information.
1:39
1:40 If you are looking for skins or missions,
1:48
1:49 check out the best there is:
1:57
1:58 www.1java.org
2:15


