[all]
0:00
0:05 Belgium, December 1944.
0:12
0:13 A young fighter pilot
0:20
0:21 is on his way to Asch in a C-47 Skytrain,
0:30
0:31 to join 352 fighter group,  
0:39
0:40 also known as the "blue- nosed bastards from Bodney".
0:55
0:56 You have been training for so long it seemed like forever,
1:10
1:11 but that's in the past....
1:20
1:21 you're ready for action now!
1:30
1:31 You will replace a rookie who "bought it" last week...
1:40
1:41 he didn't survive his 5th mission.
1:50 
1:51 will you survive yours?
2:00
2:01 will you become an ace?
2:10 
2:11 One thing is quite sure:
2:20 
2:21 you will your fist mission today!
2:30
2:31 when you get off the plane,
2:40 
2:41 a jeep will take you to the ops room
2:50 
2:51 where your flight leader awaits you
3:00
3:01 to brief you on your first patrol.
3:10
3:11 Welcome to forward base Y-29...
3:20 
3:21 good luck!
