[all]
0:0    
0:03  Pondìlí 2. záøí 1940
0:09   
0:10  Líbánky skonèily a teï zpìt do skuteèného svìta.
0:16
0:17  Díváš se ven z okna, pøeveleli tì k eskadøe Spitfirù
0:23
0:24  a pøemýšlíš, kterou eskadru ti pøiøadí.
0:30
0:31  "Tam dole je depo v Longfield, pane", køièící pilot, 
0:37
0:38  "... zásobují vìtšinu základen v tomto sektoru na této stranì Londýna, "
0:44 
0:45  " hlavní støedisko - moc práce... bìží to tam jako hodinky."
0:51    
0:52   "Které eskadøe velíte?"
0:58
0:59   "Ještì nevím, " odpovìdìls, "Byl jsem v 310 v Tangmere... "
1:08 
1:09   "To je Kenley... " køièí pilot,  
1:15
1:16   "oni mají Spitfiry a dvì eskadry Hurricanù."
1:22
1:23   "A to je náš domov - Biggin Hill... øíkáme mu jen ' Hill ' ..."
1:29
1:30  "... to je sektor 11 - moc práce, "
1:38
1:39  "kluci v této oblasti zadržují nejvíc bombardérù."
1:45
1:46  "Zdá se, že fric rád létá v oblasti Doveru, "
1:52  
1:53  "taky máme satelitní denní základny v Lympne a Hawkinge, "
1:59   
2:00   "fungují v podstatì od úsvitu do soumraku."
2:06
2:10  "Hill má dùkladnou údržbu v oblasti..."
2:16
2:17  "vyhrazené oblasti pro zásobování a doplnìní paliva- prostor pøezbrojování, " 
2:23
2:30  "A co ta budova tamhle?" 
2:36
2:37   "To je dispeèink RAF, pokud jde o Sector 11.... ."
2:43
2:44   "...a to je nemocnice - vážnì dobrá... "
2:50
2:51  "Dobrý znát... " odpovìdìls.
2:57	
3:00  Panorama Londýna bylo viditelné z Hill...
3:06
3:09  Mùžeš vidìt letku Spitfirù  - jen teèky v dálce,
3:15
3:16  stoupáte nad balony balonové pøehrady povìšenými nad mìstem.	
3:22   
3:26   "Dostáváme rádio-žvásty od velitele, " køièící pilot,
3:32
3:33   "Dispeèink RAF smìruje letku Spitù k objevenému náletu... "
3:39
3:40   "Bùh je provázej! A dobrý lov, " odpovìdìls. 
3:46
4:32   "Vítejte v Hillu, veliteli... " jeèí pilota.
4:38
4:42   Je na èase vrátit se k práci – Spity útoèí!  A jsi pøipraven.
4:50


