[all]
0:0    
0:03  Pond\u011Bl\u00ED 2. z\u00E1\u0159\u00ED 1940
0:09   
0:10  L\u00EDb\u00E1nky skon\u010Dily a te\u010F zp\u011Bt do skute\u010Dn\u00E9ho sv\u011Bta.
0:16
0:17  D\u00EDv\u00E1\u0161 se ven z okna, p\u0159eveleli t\u011B k eskad\u0159e Spitfir\u016F
0:23
0:24  a p\u0159em\u00FD\u0161l\u00ED\u0161, kterou eskadru ti p\u0159i\u0159ad\u00ED.
0:30
0:31  "Tam dole je depo v Longfield, pane", k\u0159i\u010D\u00EDc\u00ED pilot, 
0:37
0:38  "... z\u00E1sobuj\u00ED v\u011Bt\u0161inu z\u00E1kladen v tomto sektoru na t\u00E9to stran\u011B Lond\u00FDna, "
0:44 
0:45  " hlavn\u00ED st\u0159edisko - moc pr\u00E1ce... b\u011B\u017E\u00ED to tam jako hodinky."
0:51    
0:52  "Kter\u00E9 eskad\u0159e vel\u00EDte?"
0:58
0:59  "Je\u0161t\u011B nev\u00EDm, " odpov\u011Bd\u011Bls, "Byl jsem v 310 v Tangmere... "
1:08 
1:09  "To je Kenley... " k\u0159i\u010D\u00ED pilot,  
1:15
1:16  "oni maj\u00ED Spitfiry a dv\u011B eskadry Hurrican\u016F."
1:22
1:23  "A to je n\u00E1\u0161 domov - Biggin Hill... \u0159\u00EDk\u00E1me mu jen ' Hill ' ..."
1:29
1:30  "... to je sektor 11 - moc pr\u00E1ce, "
1:38
1:39  "kluci v t\u00E9to oblasti zadr\u017Euj\u00ED nejv\u00EDc bombard\u00E9r\u016F."
1:45
1:46  "Zd\u00E1 se, \u017Ee fric r\u00E1d l\u00E9t\u00E1 v oblasti Doveru, "
1:52  
1:53  "taky m\u00E1me satelitn\u00ED denn\u00ED z\u00E1kladny v Lympne a Hawkinge, "
1:59   
2:00  "funguj\u00ED v podstat\u011B od \u00FAsvitu do soumraku."
2:06
2:10  "Hill m\u00E1 d\u016Fkladnou \u00FAdr\u017Ebu v oblasti..."
2:16
2:17  "vyhrazen\u00E9 oblasti pro z\u00E1sobov\u00E1n\u00ED a dopln\u011Bn\u00ED paliva- prostor p\u0159ezbrojov\u00E1n\u00ED, " 
2:23
2:30  "A co ta budova tamhle?" 
2:36
2:37  "To je dispe\u010Dink RAF, pokud jde o Sector 11.... ."
2:43
2:44  "...a to je nemocnice - v\u00E1\u017En\u011B dobr\u00E1... "
2:50
2:51  "Dobr\u00FD zn\u00E1t... " odpov\u011Bd\u011Bls.
2:57	
3:00  Panorama Lond\u00FDna bylo viditeln\u00E9 z Hill...
3:06
3:09  M\u016F\u017Ee\u0161 vid\u011Bt letku Spitfir\u016F  - jen te\u010Dky v d\u00E1lce,
3:15
3:16  stoup\u00E1te nad balony balonov\u00E9 p\u0159ehrady pov\u011B\u0161en\u00FDmi nad m\u011Bstem.	
3:22   
3:26  "Dost\u00E1v\u00E1me r\u00E1dio-\u017Ev\u00E1sty od velitele, " k\u0159i\u010D\u00EDc\u00ED pilot,
3:32
3:33  "Dispe\u010Dink RAF sm\u011Bruje letku Spit\u016F k objeven\u00E9mu n\u00E1letu... "
3:39
3:40  "B\u016Fh je prov\u00E1zej! A dobr\u00FD lov, " odpov\u011Bd\u011Bls. 
3:46
4:32  "V\u00EDtejte v Hillu, veliteli... " je\u010D\u00ED pilota.
4:38
4:42  Je na \u010Dase vr\u00E1tit se k pr\u00E1ci – Spity \u00FAto\u010D\u00ED!  A jsi p\u0159ipraven.
4:50


