[all]
0:0    
0:05   St\u0159eda, 10. \u010Dervenec 1940 
0:15   
0:16   Velk\u00E9 formace letadel se houfuj\u00ED na obloze nad Laman\u0161sk\u00FDm pr\u016Flivem...
0:26
0:30   ... hukot jejich motor\u016F se val\u00ED nap\u0159\u00ED\u010D de\u0161tivou, v\u011Btrnou oblohou...
0:40   
0:41   Kdy\u017E se letadla zjev\u00ED z mrak\u016F a mlhy, 
0:51
0:52   prozrad\u00ED svou toto\u017Enost...
0:62  
0:58   ... neobvyk\u00E1 pod\u00EDvan\u00E1 na britsk\u00E9m pob\u0159e\u017E\u00ED... bombard\u00E9ry Luftwaffe!
1:08   
1:19   Takov\u00E1 pozorov\u00E1n\u00ED jako toto jsou v\u0161ude nad Velkou Brit\u00E1nii,
1:29   
1:30   ale Britov\u00E9 tomu \u010Del\u00ED s neochv\u011Bjn\u00FDm vzdorem a tradi\u010Dn\u00EDm bohorovn\u00FDm klidem.
1:40
1:50   Luftwaffe bombarduje cel\u00E9 britsk\u00E9 pob\u0159e\u017E\u00ED...
2:00   
2:55   St\u00EDha\u010Di RAF se rvou na potk\u00E1n\u00ED a dot\u00EDraj\u00ED na bombard\u00E9ry
3:05
3:10   \u0158\u00EDzen\u00ED RAF znovu vys\u00EDl\u00E1 hl\u00EDdkuj\u00EDc\u00ED st\u00EDha\u010De, aby \u00FAto\u010Dili na bombard\u00E9ry...
3:20
3:21   ...rychle p\u0159il\u00E9taj\u00ED a rozr\u00E1\u017E\u00ED nep\u0159\u00E1telsk\u00E9 formace...       
3:31
4:05   Bitva o Francii skon\u010Dila...
4:15
4:20   BITVA O BRIT\u00C1NII za\u010Dala!
4:30
4:35   Sko\u010Dte do sv\u00FDch letadel ml\u00E1de\u017Ei, m\u00E1me pr\u00E1ci!
4:45	