[all]
0:0    
0:03  Monday, September 2nd, 1940
0:09   
0:10  The Honeymoon was over and now it was back to the real world.
0:16
0:17  You looked out the window at the passing squadron of Spitfires
0:23
0:24  and wondered if it was the squadron you'd be assigned to.
0:30
0:31  "That's the depot at Longfield down there, Sir", shouted the pilot, 
0:37
0:38  "...supplies most of the bases in this sector, this side of London," 
0:44 
0:45  "a major hub - very busy... it runs 'round the clock."
0:51    
0:52   "What squadron are you with, Commander?" 
0:58
0:59   "Not sure yet," you replied, "I was with 601 at Tangmere..." 
1:08 
1:09   "That's Kenley over there..." shouted the pilot,  
1:15
1:16   "they've got a Spitfire and two Hurricane squadrons."
1:22
1:23   "And that's home - Biggin Hill... most just call it 'The Hill'..."
1:29
1:30  "...it's the Sector field for Sector 11 - very busy here,"
1:38
1:39  "the Lads deal with alot of bomber interceptions in this area."
1:45
1:46  "It seems the Jerrys like to come across in the Dover area,"
1:52  
1:53  "so we have satellite day-bases at Lympne and Hawkinge," 
1:59   
2:00   "that operate basically from dawn to dusk."
2:06
2:10  "The Hill has a massive maintenance area..."
2:16
2:17  "a dedicated cargo area and a refueling-rearming flightline area," 
2:23
2:30  "And what's that building over there?" You asked.
2:36
2:37   "That's RAF Control, for all of Sector 11...."
2:43
2:44   "...and that's the base hospital over there - a really good one..."
2:50
2:51  "Good to know..." you replied. You hoped you'd never need it.
2:57	
3:00  The skyline of London was visible from the Hill...
3:06
3:09  You could see the flight of Spitfires  - just specs in the distance,
3:15
3:16  climbing above the barrage balloons that hung over the city.	
3:22   
3:26   "Radio chatter coming in Commander, " shouted the pilot,
3:32
3:33   "RAF Control is routing that flight of Spits to an incoming raid..."
3:39
3:40   "Godspeed and good hunting to them," you replied.  
3:46
4:32   "Welcome to the Hill, Commander..." yelled the pilot.
4:38
4:42   Time to get back to work - Spit N' Fire!  And you were ready.
4:50


