[all]
0:0    
0:05   Støeda, 10. èervenec 1940 
0:15   
0:16   Velké formace letadel se houfují na obloze nad Lamanšským prùlivem...
0:26
0:30   ... hukot jejich motorù se valí napøíè deštivou, vìtrnou oblohou...
0:40   
0:41   Když se letadla zjeví z mrakù a mlhy,  
0:51
0:52   prozradí svou totožnost...
0:62  
0:58   ... neobvyklá podívaná na britském pobøeží... bombardéry Luftwaffe!
1:08   
1:19   Taková pozorování jako toto jsou všude nad Velkou Británii,
1:29   
1:30   ale Britové tomu èelí s neochvìjným vzdorem a tradièním bohorovným klidem.
1:40
1:50   Luftwaffe bombarduje celé britské pobøeží...
2:00   
2:55   Stíhaèi RAF se rvou na potkání a dotírají na bombardéry
3:05
3:10   Øízení RAF znovu vysílá hlídkující stíhaèe, aby útoèili na bombardéry...
3:20
3:21   ...rychle pøilétají a rozráží nepøátelské formace...       
3:31
4:05   Bitva o Francii skonèila...
4:15
4:20   BITVA O BRITÁNII zaèala!
4:30
4:35  Skoète do svých letadel mládeži, máme práci!
4:45	