[all]
0:0    
0:05   Wednesday, July 10th 1940  
0:15   
0:16   Large formations of aircraft crowd the skies over the English Channel...
0:26
0:30   ...the drone of their engines rolls across the rainy, windswept skies...
0:40   
0:41   As the planes unveil themselves from the clouds and mist,
0:51
0:52   they reveal their identity...
0:62  
0:58   ...a sight unfamiliar to the British coastline... Luftwaffe Bombers!
1:08   
1:19   Sightings like this one were occuring all across Great Britain,
1:29   
1:30   but the British people faced it with unwavering defiance and the traditional stiff upper lip.
1:40
1:50   The Luftwaffe hit targets up and down the British coastline...
2:00   
2:55   RAF fighters scramble to meet and engage the bombers
3:05
3:10   RAF Control re-routes fighters on patrol to engage the bombers...
3:20
3:21   ...arriving quickly, they slash through the enemy formations...       
3:31
4:05   The Battle of France has ended...
4:15
4:20   The BATTLE of BRITAIN has Begun!
4:30
4:35  Get to your planes Lads, we have a job to do!
4:45	