[all]
0:0    
0:03  V sobotu 7. záøí 1940, Luftwaffe zmìnila taktiku.
0:09   
0:10  Zamìnila vyèerpávání a bití základen RAF,
0:16
0:17  za útok nepøekonatelné velikosti na Londýn.
0:23
0:24  Útok mìl v úmyslu rozdrtit vùli Velké Británie bojovat...
0:30
0:31  ...a ponièenou RAF zcela pøekvapit.
0:37
0:38  Bylo zaznamenáno až 350 nepøátelských letadel podílejících se na náletu,
0:44 
0:45  který vytvoøil rozsáhlé škody všude v Londýnì.
0:51    
0:52  RAF poslala stíhaèe zadržet bombardéry, dosáhly na nì
0:58
0:59  až poté co bombardéry již udeøily na Londýn.
1:08 
1:09  Luftwaffe ztratila 74 letadel pøi tomto náletu a pravdìpodobnì dalších 34 strojù,
1:15
1:16  zatímco RAF ztratila 27 letadel... jen 14 pilotù bylo ztraceno.
1:22
1:23  Vzhledem k okolnostem to byl ohromující úspìch,
1:29
1:30  Luftwaffe plánovala další masivní nálety,
1:38
1:39  plnì doufajíc, že hrubou silou znièí britského ducha.
1:45
1:46  Byla to pøíprava pro invazi pod názvem Operace Lvoun a
1:52  
1:53  v Reichu byli pøesvìdèeni, že mohou lynèovat špendlíkem 
1:59   
2:00  a pøipravit si pozici k podrobení Britù.
2:06
2:10  Pøi drcení britského commonwealthu...
2:16
2:17  ... Luftwaffe netrpìlivì zmìnila taktiku, umožnila oddech
2:23
2:24  od jistého naprostého kolapsu, vyèerpané a zbité RAF. 
2:30
2:31  V nedìli 15. záøí 1940, Luftwaffe vypouští
2:37
2:38  rekordních 450 letadel na nálet na Londýn.
2:44
2:51  Tentokrát nemìla RAF žádné pochyby kam nálet smìøuje.
2:57	
3:00  A tentokrát... byla RAF pøipravená.
3:06
3:09  RAF dala krycí název nové taktice "The Big Wing"...
3:15
3:16  ...zabrala precizní koordinace i èas vše øádnì provést,	
3:22   
3:26  jednotlivé letky vytvoøily ve vzduchu superformaci – jak bylo naplánované. 
3:32
3:33  RAF se setkala s èelem náletu s rekordními 160 stíhaèi...
3:39
3:40  ...všechno ze sektoru 11 i zapùjèené ze sektoru 12...  
3:46
3:47  Týden bez harašení umožnil dostateènou dobu pro regeneraci
3:53
3:54  pro celou RAF - jejich základny, posádky a letadla.
4:00
4:01  Hromadný úder RAF znamenala pro Luftwaffe ohromující ránu,     
4:07
4:13  ztrátu 176 letadel - (124 bombardérù & 53 stíhaèù)... a pravdìpodobnì dalších 41 letadel.
4:19
4:20  To bylo drtivé vítìzství pro RAF, které ztratilo jen 25 letadel.
4:26
4:27  Reich nemohl riskovat opakování takových ztrát... 
4:33
4:34  ...to byl poslední nálet Luftwaffe za denního svìtla v této velikosti.
4:40
4:41  Regenerace RAF pokraèovala a sílila...
4:47

