[all]
0:0    
0:03  V sobotu 7. z\u00E1\u0159\u00ED 1940, Luftwaffe zm\u011Bnila taktiku.
0:09   
0:10  Zam\u011Bnila vy\u010Derp\u00E1v\u00E1n\u00ED a bit\u00ED z\u00E1kladen RAF,
0:16
0:17  za \u00FAtok nep\u0159ekonateln\u00E9 velikosti na Lond\u00FDn.
0:23
0:24  \u00DAtok m\u011Bl v \u00FAmyslu rozdrtit v\u016Fli Velk\u00E9 Brit\u00E1nie bojovat...
0:30
0:31  ...a poni\u010Denou RAF zcela p\u0159ekvapit.
0:37
0:38  Bylo zaznamen\u00E1no a\u017E 350 nep\u0159\u00E1telsk\u00FDch letadel pod\u00EDlej\u00EDc\u00EDch se na n\u00E1letu,
0:44 
0:45  kter\u00FD vytvo\u0159il rozs\u00E1hl\u00E9 \u0161kody v\u0161ude v Lond\u00FDn\u011B.
0:51    
0:52  RAF poslala st\u00EDha\u010De zadr\u017Eet bombard\u00E9ry, dos\u00E1hly na n\u011B
0:58
0:59  a\u017E pot\u00E9 co bombard\u00E9ry ji\u017E ude\u0159ily na Lond\u00FDn.
1:08 
1:09  Luftwaffe ztratila 74 letadel p\u0159i tomto n\u00E1letu a pravd\u011Bpodobn\u011B dal\u0161\u00EDch 34 stroj\u016F,
1:15
1:16  zat\u00EDmco RAF ztratila 27 letadel... jen 14 pilot\u016F bylo ztraceno.
1:22
1:23  Vzhledem k okolnostem to byl ohromuj\u00EDc\u00ED \u00FAsp\u011Bch,
1:29
1:30  Luftwaffe pl\u00E1novala dal\u0161\u00ED masivn\u00ED n\u00E1lety,
1:38
1:39  pln\u011B doufaj\u00EDc, \u017Ee hrubou silou zni\u010D\u00ED britsk\u00E9ho ducha.
1:45
1:46  Byla to p\u0159\u00EDprava pro invazi pod n\u00E1zvem Operace Lvoun a
1:52  
1:53  v Reichu byli p\u0159esv\u011Bd\u010Deni, \u017Ee mohou lyn\u010Dovat \u0161pendl\u00EDkem 
1:59   
2:00  a p\u0159ipravit si pozici k podroben\u00ED Brit\u016F.
2:06
2:10  P\u0159i drcen\u00ED britsk\u00E9ho commonwealthu...
2:16
2:17  ... Luftwaffe netrp\u011Bliv\u011B zm\u011Bnila taktiku, umo\u017Enila oddech
2:23
2:24  od jist\u00E9ho naprost\u00E9ho kolapsu, vy\u010Derpan\u00E9 a zbit\u00E9 RAF. 
2:30
2:31  V ned\u011Bli 15. z\u00E1\u0159\u00ED 1940, Luftwaffe vypou\u0161t\u00ED
2:37
2:38  rekordn\u00EDch 450 letadel na n\u00E1let na Lond\u00FDn.
2:44
2:51  Tentokr\u00E1t nem\u011Bla RAF \u017E\u00E1dn\u00E9 pochyby kam n\u00E1let sm\u011B\u0159uje.
2:57	
3:00  A tentokr\u00E1t... byla RAF p\u0159ipraven\u00E1.
3:06
3:09  RAF dala kryc\u00ED n\u00E1zev nov\u00E9 taktice "The Big Wing"...
3:15
3:16  ...zabrala precizn\u00ED koordinace i \u010Das v\u0161e \u0159\u00E1dn\u011B prov\u00E9st,	
3:22   
3:26  jednotliv\u00E9 letky vytvo\u0159ily ve vzduchu superformaci – jak bylo napl\u00E1novan\u00E9. 
3:32
3:33  RAF se setkala s \u010Delem n\u00E1letu s rekordn\u00EDmi 160 st\u00EDha\u010Di...
3:39
3:40  ...v\u0161echno ze sektoru 11 i zap\u016Fj\u010Den\u00E9 ze sektoru 12...  
3:46
3:47  T\u00FDden bez hara\u0161en\u00ED umo\u017Enil dostate\u010Dnou dobu pro regeneraci
3:53
3:54  pro celou RAF - jejich z\u00E1kladny, pos\u00E1dky a letadla.
4:00
4:01  Hromadn\u00FD \u00FAder RAF znamenala pro Luftwaffe ohromuj\u00EDc\u00ED r\u00E1nu,     
4:07
4:13  ztr\u00E1tu 176 letadel - (124 bombard\u00E9r\u016F & 53 st\u00EDha\u010D\u016F)... a pravd\u011Bpodobn\u011B dal\u0161\u00EDch 41 letadel.
4:19
4:20  To bylo drtiv\u00E9 v\u00EDt\u011Bzstv\u00ED pro RAF, kter\u00E9 ztratilo jen 25 letadel.
4:26
4:27  Reich nemohl riskovat opakov\u00E1n\u00ED takov\u00FDch ztr\u00E1t... 
4:33
4:34  ...to byl posledn\u00ED n\u00E1let Luftwaffe za denn\u00EDho sv\u011Btla v t\u00E9to velikosti.
4:40
4:41  Regenerace RAF pokra\u010Dovala a s\u00EDlila...
4:47

