[all]
0:0    
0:05   Sobota, 27. èervenec 1940  20:00 hod.
0:15   
0:16   V celém vyèerpaném mìstì Doveru se lidé vracejí do svých ztemnìlých domovù, 
0:22
0:23   ke svým rodinám, peèlivì zatemòují okna...
0:29   
0:32   Ulice Doveru zùstávají prázdné...
0:38
0:39   s výjimkou osamìlých dìlnických vlakù, zvláštních autobusù a jednoho èi dvou taxi.
0:45  
0:46   Ale pøístav Dover nikdy nespí, zùstává rušný celou noc...
0:52   
0:53   ...po ránu byly nálety, zpozdili se pøi vykládce lodí. 
1:00  
1:20   Dnes v noci se nebude v Doveru odpoèívat...
1:26
1:30   Luftwaffe ale mìla jiné plány...
1:36
1:37   Znovu chystají nálet na pøístav Dover, podruhé v jednom dni.
1:43   
1:44   Požáry uhasly, dokonce i dým se rozplynul... ve tmì se vše skrylo.
1:50
2:00   Z dálky vypadal Dover ospalý a nic netušící... 
2:06
2:07   ...ale zdání mùže nebezpeènì klamat.
2:13
2:20   Dover se rychle probudil a bránil se.
2:26
2:40   Takový jsou Britové... pružní, neoblomní, houževnatí.
3:00
	