[all]
0:0    
0:03  Saturday, September 7th, 1940, the Luftwaffe changed tactics.
0:09   
0:10  Switching focus from the exhausted and battered RAF bases,
0:16
0:17  the Luftwaffe launched an attack unparalleled in size, on London.
0:23
0:24  The attack was designed to crush Great Britain's will to fight...
0:30
0:31  ...and caught the ravaged RAF completely by surprise.
0:37
0:38  A record number of 350 enemy aircraft participated in the raid,
0:44 
0:45  which created extensive damage throughout London.
0:51    
0:52   RAF fighters sent to intercept the bombers, did not reach them
0:58
0:59   until after the bombers had already struck London. 
1:08 
1:09   The Luftwaffe lost 74 aircraft on that raid, another 34 probable, 
1:15
1:16   while the RAF had lost 27 aircraft... only 14 pilots were lost.
1:22
1:23   Considering it an overwhelming success, 
1:29
1:30  the Luftwaffe planned another massive raid,
1:38
1:39  fully expecting the brute force of it, to destroy the British spirit.
1:45
1:46  Time was running out for the Operation Sealion invasion and
1:52  
1:53  the Reich was convinced  this could be the lynch-pin,  
1:59   
2:00   that would help them keep their time table to conquer the British.
2:06
2:10  While a crushing blow to the British commonwealth... 
2:16
2:17  ...the Luftwaffe's impatient change of tactics, was a reprieve 
2:23
2:24  from certain total-collapse, of the exhausted and battered RAF. 
2:30
2:31   Sunday, September 15th, 1940, the Luftwaffe launches 
2:37
2:38   a record-breaking 450 aircraft on a raid against London.
2:44
2:51  This time, the RAF had no doubts where the raid was headed.
2:57	
3:00  And this time... the RAF was prepared.
3:06
3:09  The RAF nicknamed the new tactic "The Big Wing"...
3:15
3:16  ...it took precise coordination and time to execute properly,	
3:22   
3:26   but suprisingly, it formed-up perfectly - as planned. 
3:32
3:33   The RAF met the raid head-on, with a record 160 fighters...
3:39
3:40   ...everything from sector 11 and a loan from sector 12...  
3:46
3:47  A week without harrassment went a long way to recovery
3:53
3:54  for the RAF as a whole - their bases, aircrews and aircraft.
4:00
4:01   Hitting en-masse, the RAF dealt the Luftwaffe a staggering blow     
4:07
4:13  of 176 losses - (124 bombers & 53 fighters)...  plus 41 probable.
4:19
4:20   It was a smashing victory for the RAF, who lost only 25 aircraft.
4:26
4:27   The Reich could not risk a repeat of those kinds of losses... 
4:33
4:34   ...it would be the last Luftwaffe daylight raid of that magnitude.
4:40
4:41  Still recovering, the RAF would continue to grow stronger...
4:47

