[all]
0:0    
0:05   Saturday, July 27th 1940  8:30pm
0:15   
0:16   All over the weary town of Dover, people returned to their darkened homes, 
0:22
0:23   to their families, careful that no light crept from the window shades...
0:29   
0:32   The streets of Dover remain empty...
0:38
0:39   except for a lone commuter train, the odd bus and a cab or two.
0:45  
0:46   But Dover's harbor never sleeps, it remains busy throughout the night...
0:52   
0:53   ...and with the day's earlier raid, they were hours behind. 
1:00  
1:20   There would be no rest for Dover tonight...
1:26
1:30   The Luftwaffe had other plans...
1:36
1:37   They were going to hit Dover Harbor again, the second time in the same day.
1:43   
1:44   The previous fires were out, even the smoke was gone... in the dark, all was hidden.
1:50
2:00   On approach, the target of Dover looked sleepy and unsuspecting... 
2:06
2:07   ...but appearances can be dangerously deceiving.
2:13
2:20   Dover quickly came to life to defend itself.
2:26
2:40   Such were the British people... resilient, unwavering, tenacious.
3:00
	