[all]
0:0    
0:05   Sobota, 27. \u010Dervenec 1940  20:00 hod.
0:15   
0:16   V cel\u00E9m vy\u010Derpan\u00E9m m\u011Bst\u011B Doveru se lid\u00E9 vrac\u00ED do sv\u00FDch ztemn\u011Bl\u00FDch domov\u016F, 
0:22
0:23   ke sv\u00FDm rodin\u00E1m, pe\u010Dliv\u011B zatem\u0148uj\u00ED okna...
0:29   
0:32   Ulice Doveru z\u016Fst\u00E1vaj\u00ED pr\u00E1zdn\u00E9...
0:38
0:39   s v\u00FDjimkou osam\u011Bl\u00FDch d\u011Blnick\u00FDch vlak\u016F, zvl\u00E1\u0161tn\u00EDch autobus\u016F a jednoho \u010Di dvou taxi.
0:45  
0:46   Ale p\u0159\u00EDstav Dover nikdy nesp\u00ED, z\u016Fst\u00E1v\u00E1 ru\u0161n\u00FD celou noc...
0:52   
0:53   ...po r\u00E1nu byly n\u00E1lety, zpozdili se p\u0159i vykl\u00E1dce lod\u00ED. 
1:00  
1:20   Dnes v noci se nebude v Doveru odpo\u010D\u00EDvat...
1:26
1:30   Luftwaffe ale m\u011Bla jin\u00E9 pl\u00E1ny...
1:36
1:37   Znovu chystaj\u00ED n\u00E1let na p\u0159\u00EDstav Dover, podruh\u00E9 v jednom dni.
1:43   
1:44   Po\u017E\u00E1ry uhasly, dokonce i d\u00FDm se rozplynul... ve tm\u011B se v\u0161e skrylo.
1:50
2:00   Z d\u00E1lky vypadal Dover ospal\u00FD a nic netu\u0161\u00EDc\u00ED... 
2:06
2:07   ...ale zd\u00E1n\u00ED m\u016F\u017Ee nebezpe\u010Dn\u011B klamat.
2:13
2:20   Dover se rychle probudil a br\u00E1nil se.
2:26
2:40   Takov\u00FD jsou Britov\u00E9... pru\u017En\u00ED, neoblomn\u00ED, hou\u017Eevnat\u00ED.
3:00
	