[all]
0:0    
0:03  Sunday Evening, August 31st, 1940,  7:30pm
0:09   
0:11  The party at the Red Lion to celebrate your promotion, 
0:18
0:19  was more importantly - Your Wedding Reception!
0:25
0:27  You didn't need Johnny's advice to know it was right, 
0:31
0:32  but it had helped to hear it from someone else. 
0:38
0:40  Over a pint at the Red Lion wasn't the most romantic way to ask, 
0:46 
0:47  by Lauren's response, you'd think you offered her the Queen's jewels.
0:53    
0:55   Sir Archibald had granted the both of you a 3 day pass 
1:01
1:02   and the two of you were anxious to make good use of it.
1:08 
1:10   You were being transferred to a Spitfire Squadron near London
1:16
1:17   and Lauren would return to Tangmere, 
1:23
1:24   so you both knew time together would be scarce.
1:30
1:32  Johnny had gotten the same promotion as you, 
1:38
1:39  and would be going to the same squadron.
1:45
1:46  It made the transfer a little less painful.
1:52  
1:54  The party over, the goodbyes made, it was time to go. 
2:00   
2:02   As you got comfortable on the transport, you realized it was the
2:08
2:09   same pilot that had bought you into Tangmere 2 months ago.
2:16
2:18   It seemed the whole world had changed in those two months, 
2:24
2:25   you wondered where you would be two months from now.
2:31
2:33   The End of Battle of Britain - Hurricane Season
2:39
2:41   Watch for - Battle of Britain - Spittin' Fire
2:47	