[all]
0:0    
0:03  Nedìle veèer, 31. srpen 1940, 19:30 hod.
0:09   
0:11  Na veèírku v Red Lion oslavují tvoje povıšení, 
0:18
0:19  mohlo by to bıt dùleitìjší - tvá svatební hostina!
0:25
0:27  Ne nepotøebuješ Jirkovu radu, e by to bylo správné, 
0:31
0:32  ale pomohlo ti slyšet to od nìkoho jiného. 
0:38
0:40  Nad pintou v Red Lion nebylo pøíliš romantické ptát se, 
0:46 
0:47  bojíš se Lauøiny odpovìdi, myslíš si, e jí nabízíš královskı dar.
0:53    
0:55   S/L Alexander Hess udìlil vám dvìma 3 denní opušák, 
1:01
1:02   u dva dny si dìláš starosti, zda uspìješ.
1:08 
1:10   Byl by jsi pøevelen k eskadøe Spitfirù u Londına
1:16
1:17   a Laura by se vrátila do Tangmere, 
1:23
1:24   oba jste vìdìli, e spolu by jste byli vzácnì.
1:30
1:32  Jirka byl taky povıšení jako ty, 
1:38
1:39  a byl by pøevelen do stejné eskadry.
1:45
1:46  Tím by pøevelení bylo o trochu ménì bolestivé.
1:52  
1:54  Veèírek na shledanou! Je èas jít. 
2:00   
2:02   Trochu jsi se uklidnil pøi jízdì, uvìdomil sis, e to bylo
2:08
2:09   stejné jako pøevelení do Tangmere pøed dvìma mìsíci.
2:16
2:18   Zdálo se, e celı svìt se zmìnil v tìch dvou mìsících, 
2:24
2:25   udivilo tì, kde jsi všude byl celé ty dva mìsíce.
2:31
2:33   Konec Bitvy o Británii – v sezónì Huricanù
2:39
2:41   Sleduj - Bitvu o Británii - Spitti útoèí
2:47	