[all]
0:0       
0:10  Saturday, November 2nd, 1940...
0:16
0:17  The Tide had changed, and in the face of adversity,
0:23
0:24  the Luftwaffe was the first to blink.  
0:30
0:31  The Reich was fighting a shrinking timetable 
0:37
0:38  and with the changing weather, their plans were falling apart...  
0:44 
0:45  Hitler's Operation Sealion was doomed to failure.
0:51    
0:52  The RAF had taken a heavy toll on Germany's bombers, 
0:58
0:59  so daylight raids consisted of fighters and fighter-bombers,
1:05 
1:06  their bigger kites would only venture out on night raids.
1:12
1:13  As you checked on the Lads your headphones crackled...
1:19
1:20  "Mother Goose to Blue Swift Leader..." 
1:26
1:27  "Blue Swift here, go ahead Mother Goose," you replied.
1:33
1:34   "Raid inbound East of Dover, 25+, angels 10, heading 352" 
1:40
1:41   "Understood Mother Goose, moving to intercept..." 
1:47  
1:48  You made a minor course adjustment to execute intercept
1:54   
1:55  and looked out over your wings to check on the Lads...
2:01    
2:05  The wingleader on your right, hand-signaled a radio change.
2:11   
2:12  You switched over to the squadron channel... 
2:18   
2:19  "Go ahead Denny..."
2:25   
2:26  "Were you listening to the BBC last night Skipper...?"
2:32  
2:33  "No Denn, I was having a quiet evening with the Mrs... why?"
2:39  
2:40  "The BBC said that the Air Ministry announced 
2:46  
2:47  that they considered the Battle Of Britain to be over..."
2:53 	
2:54  "You're bloody joking..." you replied.
3:00  
3:01  "Swear on the Queen Mum's life..."
3:07   
3:08  "Well someone forgot to tell the bloody Jerrys, didn't they..!"
3:14    
3:20  "Never in the field of human conflict was so much owed
3:26 
3:27   by so many to so few..."    ~~  Winston Churchill  ~~
3:35  



