[all]
0:0       
0:10  Sobota 2. listopadu 1940...
0:16
0:17  Doba se zmìnila a tváøí v tváø nepøízni osudu,
0:23
0:24  Luftwaffe poprvé zaváhala.
0:30
0:31  Váleènému bìsnìní Reichu odtikával èas
0:37
0:38  a se zmìnou poèasí se jejich plány hroutí...  
0:44 
0:45  Hitlerova Operace Lvoun byla odsouzena  k selhání.
0:51    
0:52  RAF zaplatila tìžkou daò za Nìmecké bombardování,
0:58
0:59  denní nálety se skládají ze stíhaèù a stíhacích bombardérù,
1:05 
1:06  jejich vìtší draci se odváží podnikat jen noèní nálety.
1:12
1:13  Pøi kontrole svých chlapcù zapraskala sluchátka...
1:19
1:20  "Mother Goose veliteli Blue Swift..."
1:26
1:27  "Blue Swift slyším, pokraèujte Mother Goose, " 
1:33
1:34  "Nálet smìøující do vnitrozemí východnì od Doveru, 25+, angels 10, smìr 352"
1:40
1:41  "Rozumím Mother Goose, smìøuji zadržet... "
1:47  
1:48  Udìlal jsi menší kursovou úpravu a pøerušil spojení
1:54   
1:55  podíval ses pøes køídla a zkontroloval kluky...
2:01    
2:05  Druhý na tebe rukou signalizoval zmìnu rádia.
2:11   
2:12  Pøeladil jsi kanál na eskadru...
2:18   
2:19  "Pokraèuj, Stando..."
2:25   
2:26  "Poslouchal jste BBC minulou noc kapitáne...?"
2:32  
2:33  "Ne, mìl jsem klidný veèer s paní... proè?"
2:39  
2:40  "BBC hlásila, že ministerstvo letectví oznámilo, 
2:46  
2:47  že považují bitvu o Británii za skonèenou... "
2:53 	
2:54  "To si dìlají srandu, né...?"
3:00  
3:01  "Pøísahám na královský život mámy... "
3:07   
3:08  "Dobrá nìkdo to zapomnìl øíct tìm zatraceným skopèákùm, že ano..! "
3:14    
3:20  "V žádném svìtovém konfliktu nedlužilo lidstvo tak moc
3:26 
3:27  tak malé skupinì lidí..." ~~  Winston Churchill  ~~
3:35  



