[all]
0:0       
0:10  Sobota 2. listopadu 1940...
0:16
0:17  Doba se zm\u011Bnila a tv\u00E1\u0159\u00ED v tv\u00E1\u0159 nep\u0159\u00EDzni osudu,
0:23
0:24  Luftwaffe poprv\u00E9 zav\u00E1hala.
0:30
0:31  V\u00E1le\u010Dn\u00E9mu b\u011Bsn\u011Bn\u00ED Reichu odtik\u00E1val \u010Das
0:37
0:38  a se zm\u011Bnou po\u010Das\u00ED  se jejich pl\u00E1ny hrout\u00ED...  
0:44 
0:45  Hitlerova Operace Lvoun byla odsouzena  k selh\u00E1n\u00ED.
0:51    
0:52  RAF zaplatila t\u011B\u017Ekou da\u0148 za N\u011Bmeck\u00E9 bombardov\u00E1n\u00ED,
0:58
0:59  denn\u00ED n\u00E1lety se skl\u00E1daj\u00ED ze st\u00EDha\u010D\u016F a st\u00EDhac\u00EDch bombard\u00E9r\u016F,
1:05 
1:06  jejich v\u011Bt\u0161\u00ED draci se odv\u00E1\u017E\u00ED podnikat jen no\u010Dn\u00ED n\u00E1lety.
1:12
1:13  P\u0159i kontrole sv\u00FDch chlapc\u016F zapraskala sluch\u00E1tka...
1:19
1:20  "Mother Goose veliteli Blue Swift..."
1:26
1:27  "Blue Swift sly\u0161\u00EDm, pokra\u010Dujte Mother Goose, " 
1:33
1:34  "N\u00E1let sm\u011B\u0159uj\u00EDc\u00ED do vnitrozem\u00ED v\u00FDchodn\u011B od Doveru, 25+, angels 10, sm\u011Br 352"
1:40
1:41  "Rozum\u00EDm Mother Goose, sm\u011B\u0159uji zadr\u017Eet... "
1:47  
1:48  Ud\u011Blal jsi men\u0161\u00ED kursovou \u00FApravu a p\u0159eru\u0161il spojen\u00ED
1:54   
1:55  pod\u00EDval ses p\u0159es k\u0159\u00EDdla a zkontroloval kluky...
2:01    
2:05  Druh\u00FD na tebe rukou signalizoval zm\u011Bnu r\u00E1dia.
2:11   
2:12  P\u0159eladil jsi kan\u00E1l na eskadru...
2:18   
2:19  "Pokra\u010Duj, Stando..."
2:25   
2:26  "Poslouchal jste BBC minulou noc kapit\u00E1ne...?"
2:32  
2:33  "Ne, m\u011Bl jsem klidn\u00FD ve\u010Der s pan\u00ED... pro\u010D?"
2:39  
2:40  "BBC hl\u00E1sila, \u017Ee ministerstvo letectv\u00ED ozn\u00E1milo, 
2:46  
2:47  \u017Ee pova\u017Euj\u00ED bitvu o Brit\u00E1nii za skon\u010Denou... "
2:53 	
2:54  "To si d\u011Blaj\u00ED srandu, n\u00E9...?"
3:00  
3:01  "P\u0159\u00EDsah\u00E1m na kr\u00E1lovsk\u00FD \u017Eivot m\u00E1my... "
3:07   
3:08  "Dobr\u00E1 n\u011Bkdo to zapomn\u011Bl \u0159\u00EDct t\u011Bm zatracen\u00FDm skop\u010D\u00E1k\u016Fm, \u017Ee ano..! "
3:14    
3:20  "V \u017E\u00E1dn\u00E9m sv\u011Btov\u00E9m konfliktu nedlu\u017Eilo lidstvo tak moc
3:26 
3:27  tak mal\u00E9 skupin\u011B lid\u00ED..." ~~  Winston Churchill  ~~
3:35  



