[all]
0:05   What General Weygand called the Battle of France is over.
0:10
0:20 But this is not the end.
0:30
0:35 It is not even the beginning of the end...
0:40
0:45  It is merely the end of the beginning.
0:50
0:55 The whole fury and might of the enemy must soon be turned on us.
1:02
1:05 Hitler knows that he will have to break us in this island to win the war.
1:10
1:13 If we can stand up to him, the life of the world may move forward into broad, sunlit uplands.
1:23
1:27 Let us therefore brace ourselves to our duties...
1:32
1:35 ...and so bear ourselves that, if the British Empire and it's Commonwealth last for a thousand years...
1:40
1:45 ..Men will still say,...
1:49
1:50 ... this was their finest hour.
1:57                                 

