[all]
0:0                                    France, October 1939
0:05
0:12 Advanced Air Strike Force H.Q., Reims
0:15
0:16 You are to take command of your old Hurricane squadron
0:19
0:20 to protect our Blenheims and Battles once the shooting war gets under way.
0:27
0:32 France now is full of contrasts...
0:34
0:35 -the grim preparations of the formidable border defences ...
0:40
0:43 ...versus the beauty and normalcy of her towns and villages.
1:05
1:09 The RAF presence in France is small...
1:15
1:20  but together with l'Armee de l'Air...
1:23
1:30   ... we must make the most of this time to gather our strength and hone our skills...
1:35
1:38 ..and so brace ourselves
1:45 
1:50 ... for the coming onslaught.
2:00
2:05    R.A.F. Pilot - France 
2:10
2:12   by FlatSpinMan
2:15
2:17   with special thanks to
2:19
2:20  Kristorf 
2:23
2:24  and 
2:26
2:30 Moselgott and Magic369
2:33
2:35 FlatSpinMan Productions MMVIII
